RocketManagement.UI/Models/ErrorViewModel.cs
namespace RocketManagement.UI.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

RocketManagement.UI/Controllers/RocketController.cs
using MediatR;
using Microsoft.AspNetCore.Mvc;
using RocketManagement.Application.Features;
using RocketManagement.Application.Features.Rocket.Commands;
using RocketManagement.Application.Features.Rocket.Dtos;
using RocketManagement.Application.Features.Rocket.Queries;

namespace RocketManagement.UI.Controllers
{
    public class RocketController : Controller
    {
        private readonly ILogger<RocketController> _logger;
        private readonly IMediator mediator;

        public RocketController(ILogger<RocketController> logger, IMediator mediator)
        {
            _logger = logger;
            this.mediator = mediator;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var result = await mediator.Send(new GetAllRocketsQuery());

            if (!result.IsSuccess)
            {
                IfNotSuccessSetErrorMessage(result);

                return View(new List<RocketDto>());
            }

            return View(result.Model);
        }

        [HttpGet]
        [Route("details")]
        public async Task<IActionResult> Details(string id)
        {
            var result = await mediator.Send(new GetAllRocketsQuery());

            if (!result.IsSuccess)
            {
                IfNotSuccessSetErrorMessage(result);

                return View(new RocketDto());
            }

            var rocket = result.Model.First(c => c.Id == id);

            return View(rocket);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("launch")]
        public async Task<IActionResult> Launch([Bind("Id")] string id)
        {
            var result = await mediator.Send(new LaunchRocketCommand() { Id = id });

            SetMessageToTempData(result);

            return RedirectToAction(nameof(Details), new { id = id });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("deploy")]
        public async Task<IActionResult> Deploy([Bind("Id")] string id)
        {
            var result = await mediator.Send(new DeployRocketCommand() { Id = id });

            SetMessageToTempData(result);

            return RedirectToAction(nameof(Details), new { id = id });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("cancellaunch")]
        public async Task<IActionResult> CancelLaunch([Bind("Id")] string id)
        {
            var result = await mediator.Send(new CancelLaunchCommand() { Id = id });

            SetMessageToTempData(result);

            return RedirectToAction(nameof(Details), new { id = id });
        }

        [HttpGet]
        [Route("show-telemetry")]
        public async Task<IActionResult> ShowTelemetry(string id)
        {
            return View();
        }

        private void SetMessageToTempData(BaseResponse response)
        {
            IfSuccessSetInformationMessage(response);
            IfNotSuccessSetErrorMessage(response);
        }

        private void IfNotSuccessSetErrorMessage(BaseResponse response)
        {
            if (!response.IsSuccess)
            {
                TempData["ErrorMessage"] = response.Message;
            }
        }

        private void IfSuccessSetInformationMessage(BaseResponse response)
        {
            if (response.IsSuccess)
            {
                TempData["InformationMessage"] = response.Message;
            }
        }
    }
}

RocketManagement.UI/ViewComponents/WeatherViewComponent.cs
using MediatR;
using Microsoft.AspNetCore.Mvc;
using RocketManagement.Application.Features;
using RocketManagement.Application.Features.Weather.Dtos;
using RocketManagement.Application.Features.Weather.Queries;

namespace RocketManagement.UI.ViewComponents
{
    public class WeatherViewComponent : ViewComponent
    {
        private readonly IMediator mediator;

        public WeatherViewComponent(IMediator mediator)
        {
            this.mediator = mediator;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var result = await mediator.Send(new GetWeatherQuery());

            if (result.IsSuccess)
            {
                return await Task.FromResult((IViewComponentResult)View(result.Model));
            }
            else
            {
                SetErrorMessage(result);

                return await Task.FromResult((IViewComponentResult)View(new WeatherDto()));
            }
        }

        private void SetErrorMessage(BaseResponse response)
        {
            TempData["ErrorMessage"] = response.Message;
        }
    }
}

RocketManagement.UI/Views/Rocket/Details.cshtml
@using RocketManagement.Application.Features.Rocket.Dtos
@model RocketDto

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@await Html.PartialAsync("~/Views/Shared/PartialViews/Message.cshtml")

<br />

<div>
    @(await Component.InvokeAsync("Weather"))
</div>

<form method="post" action="">

    <div class="card">
        <div class="card-header">
            Rocket Information
        </div>
        <div class="card-body">
            <div class="row">
                <div class="col-sm-2 border border-secondary">Rocket Id</div>
                <div class="col-sm-2 border border-secondary">
                    @Html.DisplayFor(model => model.Id)
                    @Html.HiddenFor(model => model.Id)
                </div>

                <div class="col-sm-2 border border-secondary">Rocket Model</div>
                <div class="col-sm-2 border border-secondary"> @Html.DisplayFor(model => model.RocketModel)</div>

                <div class="col-sm-2 border border-secondary">Status</div>
                <div class="col-sm-2 border border-secondary">
                    @Html.DisplayFor(model => model.Status)
                    @Html.HiddenFor(model => model.Status)
                </div>
                <div class="col-sm-2 border border-secondary">Mass</div>
                <div class="col-sm-2 border border-secondary">
                    @Html.DisplayFor(model => model.Mass)
                    @Html.HiddenFor(model => model.Mass)
                </div>

                <div class="col-sm-2 border border-secondary">Altitude</div>
                <div class="col-sm-2 border border-secondary">
                    @Html.DisplayFor(model => model.Altitude)
                    @Html.HiddenFor(model => model.Altitude)
                </div>

                <div class="col-sm-2 border border-secondary">Speed</div>
                <div class="col-sm-2 border border-secondary">
                    @Html.DisplayFor(model => model.Speed)
                    @Html.HiddenFor(model => model.Speed)
                </div>
                <div class="col-sm-2 border border-secondary">Acceleration</div>
                <div class="col-sm-2 border border-secondary">
                    @Html.DisplayFor(model => model.Acceleration)
                    @Html.HiddenFor(model => model.Acceleration)
                </div>

                <div class="col-sm-2 border border-secondary">Thrust</div>
                <div class="col-sm-2 border border-secondary">
                    @Html.DisplayFor(model => model.Thrust)
                    @Html.HiddenFor(model => model.Thrust)
                </div>

                <div class="col-sm-2 border border-secondary">Temperature</div>
                <div class="col-sm-2 border border-secondary">
                    @Html.DisplayFor(model => model.Temperature)
                    @Html.HiddenFor(model => model.Temperature)
                </div>
            </div>
        </div>
    </div>

    <div class="card">
        <div class="card-header">
            Payload
        </div>
        <div class="card-body">
            <div class="row">
                <div class="col-sm-6 border border-secondary">Description</div>
                <div class="col-sm-6 border border-secondary"> @Html.DisplayFor(model => model.Payload.Description)</div>
                <div class="col-sm-6 border border-secondary">Weight</div>
                <div class="col-sm-6 border border-secondary"> @Html.DisplayFor(model => model.Payload.Weight)</div>
            </div>
        </div>
    </div>

    <br />

    <div class="card">
        <div class="card-header">
            Telemetery
        </div>
        <div class="card-body">
            <div class="row">
                <div class="col-sm-6 border border-secondary">Host</div>
                <div class="col-sm-6 border border-secondary"> @Html.DisplayFor(model => model.Telemetry.Host)</div>
                <div class="col-sm-6 border border-secondary">Port</div>
                <div class="col-sm-6 border border-secondary"> @Html.DisplayFor(model => model.Telemetry.Port)</div>
            </div>
        </div>
    </div>

    <br />

    <div class="card">
        <div class="card-header">
            Time stamps
        </div>
        <div class="card-body">
            <div class="row">
                <div class="col-sm-3 border border-secondary">Launched Time</div>
                <div class="col-sm-3 border border-secondary">@Html.DisplayFor(model => model.Timestamps.Launched)</div>
                <div class="col-sm-3 border border-secondary">Deployed Time</div>
                <div class="col-sm-3 border border-secondary">@Html.DisplayFor(model => model.Timestamps.Deployed)</div>
                <div class="col-sm-3 border border-secondary">Failed Time</div>
                <div class="col-sm-3 border border-secondary">@Html.DisplayFor(model => model.Timestamps.Failed)</div>
                <div class="col-sm-3 border border-secondary">Cancelled Time</div>
                <div class="col-sm-3 border border-secondary">@Html.DisplayFor(model => model.Timestamps.Cancelled)</div>
            </div>
        </div>
    </div>

    <br />

    <div class="btn-group" role="group" aria-label="Button group with nested dropdown">

        <a href='@Url.Action("ShowTelemetry", "Rocket",new { id=Model.Id })'>
            <input type='button' value='Show Telemetry' class="btn btn-primary" />
        </a>

        <div class="btn-group" role="group">
            <button id="btnGroupDrop1" type="button" class="btn btn-primary dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
                Commands
            </button>
            <ul class="dropdown-menu" aria-labelledby="btnGroupDrop1">
                <li> <input type="submit" value="Launch" asp-action="Launch" class="dropdown-item" /></li>
                <li> <input type="submit" value="Deploy" asp-action="Deploy" class="dropdown-item" /></li>
                <li> <input type="submit" value="Cancel Launch" asp-action="CancelLaunch" class="dropdown-item" /></li>
            </ul>
        </div>

        <a href='@Url.Action("Index", "Rocket")'>
            <input type='button' value='Back To Rocket List' class="btn btn-primary" />
        </a>
    </div>
</form>

RocketManagement.UI/Views/Rocket/Index.cshtml
@using RocketManagement.Application.Features.Rocket.Dtos
@model IEnumerable<RocketDto>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@await Html.PartialAsync("~/Views/Shared/PartialViews/Message.cshtml")

<br />

<a href='/healthchecks-ui'>
    <input type='button' value='Show Health Check' class="btn btn-primary" />
</a>

<table class="table table-bordered">
    <thead class="thead-dark">
        <tr>
            <th scope="col">
                Rocket Id
            </th>
            <th scope="col">
                Rocket Model
            </th>
            <th scope="col">
                Mass
            </th>
            <th scope="col">
                Status
            </th>
            <th scope="col">
                Altitude
            </th>
            <th scope="col">
                Speed
            </th>
            <th scope="col">
                Acceleration
            </th>
            <th scope="col">
                Thrust
            </th>
            <th scope="col">
                Temperature
            </th>
            <th scope="col"></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.RocketModel)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Mass)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Status)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Altitude)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Speed)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Acceleration)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Thrust)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Temperature)
                </td>
                <td>
                    @Html.ActionLink("Details", "Details", new { id=item.Id })
                </td>
            </tr>
        }
    </tbody>
</table>

RocketManagement.UI/Views/Rocket/ShowTelemetry.cshtml
@{
    ViewData["Title"] = "ShowTelemetry";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <div class="row">
        <table id="telemetryTable">
            <thead>
                <tr>
                    <th>Rocket System Id</th>
                    <th>Altitude</th>
                    <th>Speed</th>
                    <th>Acceleration</th>
                    <th>Thrust</th>
                    <th>Temperature</th>
                </tr>
            </thead>
            <tbody>
            </tbody>
        </table>
        <ul id="messagesList"></ul>
    </div>
</div>

<script src="~/lib/microsoft/signalr/dist/browser/signalr.js"></script>
<script src="~/js/telemetrylistener.js"></script>

RocketManagement.UI/Views/Shared/Components/Weather/Default.cshtml
@using RocketManagement.Application.Features.Weather.Dtos
@model WeatherDto

<div class="card">
    <div class="card-header">
        Weather
    </div>
    <div class="card-body">
        <div class="row">
            <div class="col-sm-3 border border-secondary">Temperature</div>
            <div class="col-sm-3 border border-secondary"> @Html.DisplayFor(model => model.Temperature)</div>
            <div class="col-sm-3 border border-secondary">Humidity</div>
            <div class="col-sm-3 border border-secondary">@Html.DisplayFor(model => model.Humidity)</div>
            <div class="col-sm-3 border border-secondary">Pressure</div>
            <div class="col-sm-3 border border-secondary">@Html.DisplayFor(model => model.Pressure)</div>
            <div class="col-sm-3 border border-secondary">Time</div>
            <div class="col-sm-3 border border-secondary">@Html.DisplayFor(model => model.Time)</div>
        </div>
    </div>
</div>

RocketManagement.UI/Views/Shared/PartialViews/Message.cshtml
@if (@TempData["ErrorMessage"] != null)
{
    <div class="alert alert-danger" role="alert">
        @TempData["ErrorMessage"]
    </div>
}

@if (@TempData["InformationMessage"] != null)
{
    <div class="alert alert-success" role="alert">
        @TempData["InformationMessage"]
    </div>
}

RocketManagement.UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Rocket Management</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/RocketManagement.UI.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Rocket" asp-action="Index">Rocket Management</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
     <script src="~/lib/jquery-ajax-unobtrusive/jquery.unobtrusive-ajax.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>